import {ThemeStyle} from '../types/ThemeStyle';

const theme: ThemeStyle = {
  FONT_SIZE_TINY: 13,
  FONT_SIZE_BODY: 15,
  FONT_SIZE_TITLE: 17,
  FONT_SIZE_HUGE: 34,

  COLOR_PRIMARY: '#AD70FB',
  COLOR_PRIMARY_VAR: '#771EE7',
  COLOR_SECONDARY: '#23CE6B',
  COLOR_ERROR: '#FF376C',

  COLOR_BACKGROUND: '#242124',
  COLOR_SURFACE_DEEP: '#363336',
  COLOR_SURFACE_MID: '#3C393C',
  COLOR_SURFACE_HIGH: '#454245',

  TEXT_WHITE: '#FFFFFF',
  TEXT_BLACK: '#000000',
};

export default theme;
